### ISSUE TITLE
The site http://getelegant.com/ is offline

### ISSUE THREAD

**Issue by diogowernik** [digital-flowers/elegant#2]
Hi, i am trying to access the site http://getelegant.com/ for few days and it doesn't load...

In the site there are a lot of good tips that would be great to have access when using the framework

Thanks

**Comment by digital-flowers** [comment]
Hi Diogo,
I am Fareed, I am very happy to here this from you, actually we will continue working on this framework project but i have attended an acceleration program in San Fransisco for 4 Months and i was very busy working on my own startup so i just realised that my credit card auto-renew didn’t work on the hosting company (Amazone AWS) for some reason ;(
anyway i think i will try my best to make the site online before 3rd of Nov also i will upload a new update including a new layer to enable web sockets and describe how it will be super easy to create a chat application using elegant framework, really sorry for that interruption :/

**Comment by diogowernik** [comment]
amazing :) 

thanks a lot, is a very good project and i really liked it!

will be wating

best wishes

**Comment by digital-flowers** [comment]
Hi, 
sorry for the delay the framework doc is online now at http://getelegant.com
also we have added the documentation full code to github at https://github.com/digital-flowers/elegant-doc
again sorry for the delay

**Comment by diogowernik** [comment]
Amazing, really thanks... I will start the test drive, and was a very good idea to add the documentation full code... will clone it also!

thanks

**Comment by digital-flowers** [comment]
you are welcome ;)
also if you like the project and you have any ideas i can add you as  a contributor :+1:
